CREATE ROLE gr_app WITH
    NOLOGIN
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    INHERIT
    NOREPLICATION
    CONNECTION LIMIT -1;
COMMENT ON ROLE gr_app IS 'Group for our CA application';


CREATE ROLE app_user WITH
    LOGIN
    NOSUPERUSER
    INHERIT
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION
    ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:TL5Ug9oXuFUg7JMUHoc1hw==$SqfoJPXa7CgQhUGFiXvKf+cI7kUGunIJu8oEMc+3ZFc=:rOU7kOnut7vCLs4+PEGApccnkBhIuBZK5curKQBrRY4=';

GRANT gr_app TO app_user;

COMMENT ON ROLE app_user IS 'User for our small application';
