version: "3.8"
services:
  postgresqldb:
    image: postgres
    container_name: ca-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_very_strong_password
    ports:
      # <Port exposed> : < PostgreSQL Port running inside container>
      - "5432:5432"
    networks:
      - postgres_network
    volumes:
      - ~/db-data:/var/lib/postgresql/data
volumes:
  db-data:

networks:
  postgres_network:
    driver: bridge
